project:
  type: book

book:
  title: "Mappeeksamen IDR4000: Kvantitativ metode og statistikk"
  author: "Kandidatsnummer: 516. Antall ord: 16 113"
  date: "2024-11-22"
  chapters:
    - index.qmd
    - 01-reliabilitet.qmd
    - 02-regression-models.qmd
    - 03-statistical-inference.qmd
    - 04-study-design.qmd
    - 05-repeated-measurements.qmd
    - 06-vitenskapsteori.qmd
    - 07-laboratory-report.qmd
    - references.qmd

bibliography: resources/bib-final.bib

format: 
  pdf:
    number-sections: true
    toc: true       # Inkluderer innholdsfortegnelse

execute: 
  warning: false
  echo: false
crossref:
  fig-title: "Figur"
  tbl-title: "Tabell"
csl: resources/apa.csl
